name: Deployment

on:
  push:
    branches: [ "main" ]

concurrency: main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
  SSH_PORT: ${{ vars.SSH_PORT }}
  SSH_USER: ${{ vars.SSH_USER }}
  SSH_IP: ${{ vars.SSH_IP }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/known_hosts
          chmod 700 ~/.ssh

      - name: List files on remote server
        run: ssh -p $SSH_PORT $SSH_USER@$SSH_IP 'cd ~/repository/laravel-api-codewithross.app && ls'
